(defvar i 1)

(defun clear-emacs-buffer ()
  (swank:eval-in-emacs
   '(progn
         (run-at-time 0 nil 'slime-repl-clear-buffer)
         nil)))

(defun uwu-boot-animation ()
  (clear-emacs-buffer)
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (sleep 4)
  (clear-emacs-buffer)
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")  
  (sleep 0.1)
  (clear-emacs-buffer)
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (format t "********************~%")
  (sleep 0.1)
  (clear-emacs-buffer)
  (format t "CUTE-DOS V4.20~%")
  (sleep 1)
  (format t "MEMORY TEST")
  (sleep 1)
  (dotimes (i 70)
    (clear-emacs-buffer)
    (format t "CUTE DOS V4.20~%")
    (format t "MEMORY TEST ")
    (format t "~d" i)
    (format t "KB OK")
    )
  (sleep 4)
  (format t ":3")
  (sleep 0.25)
  (clear-emacs-buffer)
  (dotimes (i (* 69 3))
    (format t "~x  " (random 69))
    (format t "~x  " (random 69))
    (format t "~x  " (random 69))
    (format t "~x~%" (random 69))
    (sleep 0.01)
    )
  (clear-emacs-buffer)
  (format t "LOADING UWU~%")
  (sleep 1)
  (format t "READY~%")
  (sleep 1)
  (format t "RUNNING :3~%")
  (sleep 1)
  (clear-emacs-buffer)
  )
